### ISSUE TITLE
Rewrite Firefox backend to a WebExtension

### ISSUE THREAD

**Issue by minj** [minj/foxtrick#1339]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions
Instead of #1337

**Comment by minj** [comment]
https://webextensions.uservoice.com/forums/315663-webextension-api-ideas

**Comment by minj** [comment]
https://hacks.mozilla.org/2015/10/porting-chrome-extensions-to-firefox-with-webextensions/

**Comment by minj** [comment]
http://www.arewewebextensionsyet.com/

**Comment by minj** [comment]
Problems according to: https://github.com/abarreir/crx2ff:

- [ ] `clipboardWrite`
- [ ] `optional_permissions` and `chrome.permissions.*`
- [ ] `web_accessible_resources` do not support wildcards
- [ ] `options_page`
- [ ] `homepage_url`
- [ ] `chrome.runtime.lastError`
- [ ] `chrome.runtime.getURL`
- [ ] `chrome.notifications.create` supports only `iconUrl`, `title`, and `message` (no interaction)

Additional checklist:
- [ ] `chrome.contextMenus.*` race condition
- [ ] Android support

On the whole not that bad, I'd say.

**Comment by minj** [comment]
For settings migration: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Embedded_WebExtensions

**Comment by minj** [comment]
Problems and resolutions:

## Rewrite
- [ ] `options_page`need to rewrite to `options_ui`
- [ ] `chrome.contextMenus.*` [race condition](https://bugzilla.mozilla.org/show_bug.cgi?id=1215376)
- [ ] [clipboard hack](https://stackoverflow.com/questions/3436102/copy-to-clipboard-in-chrome-extension/12693636#12693636) for  `clipboardWrite` [bug 1272869](https://bugzilla.mozilla.org/show_bug.cgi?id=1272869)

## Disable
- [ ] `chrome.notifications.create` supports only `iconUrl`, `title`, and `message` so [no interaction](https://bugzilla.mozilla.org/show_bug.cgi?id=1190681)

## Hope for best
- [ ] [Android support](https://bugzilla.mozilla.org/show_bug.cgi?id=1185785)

## Ignore
- [ ] `optional_permissions` and `chrome.permissions.*` [bug 1197420](https://bugzilla.mozilla.org/show_bug.cgi?id=1197420)

## Solved
- [x] `web_accessible_resources` [do not support wildcards](https://bugzilla.mozilla.org/show_bug.cgi?id=1217944)
- [x] `homepage_url` [bug 1223145](https://bugzilla.mozilla.org/show_bug.cgi?id=1223145)
- [x] `chrome.runtime.lastError` [bug 1190680](https://bugzilla.mozilla.org/show_bug.cgi?id=1190680)
- [x] `chrome.tabs.sendMessage` ~~[broken](https://bugzilla.mozilla.org/show_bug.cgi?id=1209869)?~~ not for me
- [x] a [problem](https://bugzilla.mozilla.org/show_bug.cgi?id=1190663) with `window.close()` in pageAction popup
- [x] `chrome.tabs.create` has [weird behavior in pageAction](https://bugzilla.mozilla.org/show_bug.cgi?id=1233326)

**Comment by minj** [comment]
Other problems and resolutions:

## Hope for best
- [ ] [Android support](https://bugzilla.mozilla.org/show_bug.cgi?id=1185785)

## Ignore
- [ ] `optional_permissions` and `chrome.permissions.*` [bug 1197420](https://bugzilla.mozilla.org/show_bug.cgi?id=1197420)

## Solved
- [x] `web_accessible_resources` [do not support wildcards](https://bugzilla.mozilla.org/show_bug.cgi?id=1217944)
- [x] `homepage_url` [bug 1223145](https://bugzilla.mozilla.org/show_bug.cgi?id=1223145)
- [x] `chrome.runtime.lastError` [bug 1190680](https://bugzilla.mozilla.org/show_bug.cgi?id=1190680)
- [x] `chrome.tabs.sendMessage` ~~[broken](https://bugzilla.mozilla.org/show_bug.cgi?id=1209869)?~~ not for me
- [x] a [problem](https://bugzilla.mozilla.org/show_bug.cgi?id=1190663) with `window.close()` in pageAction popup
- [x] `chrome.tabs.create` has [weird behavior in pageAction](https://bugzilla.mozilla.org/show_bug.cgi?id=1233326)

**Comment by minj** [comment]
Target version for permissions: v55

**Comment by minj** [comment]
moving away off of ZenHub

**Comment by minj** [comment]
No use keeping this around
